const CHAPTERS = [
  {
    id: 1, name: 'Religion & Gods', symbol: '☽', color: '#b53a20',
    question: 'What do we build when we cannot bear to build ourselves?',
    cards: [
      { title: 'The Priests', question: 'What do we build when we cannot bear to build ourselves?', aphorisms: ['Priests could claim divine rights because their clients were both ignorant and indolent. It suited the priests to perpetuate the myth of divine rights so it could trickle to the lowest strata to foreclose rebellion.','Religion is power-business; god is its luscious commodity.','Religion is for the naive; those who have realised life would not take refuge in religion.','Inability to excrete old gods is a venal ethnological defect; it can only hinder progress.'] },
      { title: 'The Hollow', question: 'Is it the hollow of the heart, or the poverty of reason, that fills a church?', aphorisms: ['Christianity and Islam will survive till there are adherents ready to perish in the name of religion.','Belief in the supernatural power, howsoever untenable, is preferred to rationalism because it fills the hollowness of the heart.','Reason, though fully understandable and logical, is dry. On the other hand, Belief in God is luscious and supports our irresponsibility and indolence.','Gods which enjoy — elope, abduct, seduce or intoxicate are preferable to ones who are prim and proper; the former create peace and content, the latter only mayhem and bloodletting.'] },
      { title: 'The Petition', question: 'Can a petition replace the labour of being human?', aphorisms: ['God is a pernicious fraud since eternity.','Worship is only acceptance. It becomes a petition when aspirations are attached.','To ask something of God is to deny humanity its due.','Let God enjoy his heaven. We can create our heaven in our minds.'] },
      { title: 'The Idol', question: 'What remains when the idol is removed?', aphorisms: ['God and Devil are necessarily same thing. People will use or abuse its aspect which suits their convenience.','Religion was, is and will be big business till humanity attains maturity.','The Buddha suffered the greatest insult when he was declared an incarnation of God.','There is infinite joy and wonder in contemplating the world around. To demean it by giving credit to a creator is blasphemy of the worst kind.'] },
      { title: 'The Space', question: 'Where does the god end and the mind begin?', aphorisms: ['Spirituality is the exegesis of physical incapacity.','Societies which give intellectual space to god will necessarily degenerate. We need to reclaim that space from god-places.','Intellectual constipation is a malaise. It is a result of inability to excrete gods.','It is a mystery why religious people are always against progress.'] },
      { title: 'The Dog', question: 'What does the dog know that the devotee does not?', aphorisms: ['Priests everywhere are wicked and cunning because of their training and their deprivations during the training.','Dogs have better understanding of human nature hence they lift their legs at smeared stone icons in the countryside.','Gods can be amusing if we have perspective; if taken seriously, they can be lethal to our wellbeing.','Scriptures should be enjoyed rather than obeyed for they are of another age; if nothing is permanent why should our morals be the same over the millennia.'] },
      { title: 'The Divine', question: 'Is the divine within, or have we given it away?', aphorisms: ['Progress can only follow after divorce from the non-rational. Gods are the biggest hindrances for development of the mind — both individual or social.','The divine is but your thought. Never debase it by fostering it on something external to you.'] }
    ]
  },
  {
    id: 2, name: 'Society & Power', symbol: '⚖', color: '#1e5c8a',
    question: 'Who benefits when the people remain still?',
    cards: [
      { title: 'The Still', question: 'Who benefits when the people remain still?', aphorisms: ['Industrial revolution was not possible in India because most thought producers were busy in Bhakti; it suited the extant political powers.','The threat of social sanctions can work only in a dictatorship.','Society will always inhibit. It is the rebels who will innovate and improvise the social milieu.','Never seek social or peer approval; it is an exersize in futility.'] },
      { title: 'The Weak', question: 'Is submission a choice, or the slow erasure of one?', aphorisms: ['Exploitation of the weak by the strong is universal; the weak can only become honourable if they rebel and ready to perish. Otherwise they deserve this exploitation.','Political power cannot sustain without cultural power. Aspirants of political power should acquire cultural hinges before taking political leap.','Politics has become the first refuge of the rogue because the electorate has turned rogue. You can glean it in daily behaviour.','Dictators are insecure and immature adults. They are scared of reason and would go to any length to hide their insecurity.'] },
      { title: 'The Chain', question: 'What does a chain look like when those inside it call it home?', aphorisms: ['Only free people can arrest the stultification of the mind.','Chains create their own fosterers.','A community which refuses to share knowledge is venal and wicked; confining of knowledge has been the bane of underdevelopment in India till recently. Vested interests would like to roll back spread of knowledge in subtle ways.','The downtrodden deserve to be that way because they forfeit self-respect all too soon. If they will, they could rebel, preferring death to their regretful lives. Suddenly they would gain respect from the milieu.'] },
      { title: 'The Ruled', question: 'Can the ruled ever speak the language of those who rule?', aphorisms: ['The fallacy of sovereignty should be debunked — for an individual to attain freedom.','The progressive groups amongst the exploited and downtrodden can never reach leadership roles unless they assume innovative cultural movement — language, vocabulary, means of communication and dissemination, mobilisation, goals. Being followers of the dominant in every aspect of life is their bane.','Mores are short-term preservatives of the humans; morals are inhibitive of progress and vitality.','To demand respect is debasing others intellect.'] },
      { title: 'The Wound', question: 'Is charity a salve, or a way of keeping the wound open?', aphorisms: ['Charity is but a sick act to support extant exploitation.'] }
    ]
  },
  {
    id: 3, name: 'Self & Wisdom', symbol: '◎', color: '#2e7a38',
    question: 'When does strength reveal itself — in comfort, or in undoing?',
    cards: [
      { title: 'The Boat', question: 'When does strength reveal itself — in comfort, or in undoing?', aphorisms: ['I claimed strength when i had been weakened the most by burdensome customs entrapping my spirit.','Ancient wisdom can only be a hindrance to freedom. You do not carry the boat on your head after crossing the river.','The pupil does not owe anything to her teacher, even gratitude, except an obligation to exceed her teacher\'s wisdom.','Happiness and contentment are by products of wisdom and understanding; the ignorant deserve their anxiety and misery.'] },
      { title: 'The Bliss', question: 'Is contentment the reward of wisdom, or its disguise?', aphorisms: ['Ignorance is bliss only for the naive; they deprive themselves of the wondrous even if sad joy that knowledge and wisdom begets.','There is no role destined for any particular role, except to be happy.','It is not sufficient to be good for achieving happiness; one needs to be intelligent also.','Character is built only in solitude just as reputations are built in social community.'] },
      { title: 'The Middle', question: 'Do we run from unhappiness, or toward an image we mistake for it?', aphorisms: ['Empathising with the weak is perpetuating her misery. Exercising her strength is the dawn of wisdom.','We need so little to be happy yet we ever run after unhappiness confounding it to be the succour.','Desire is the sole cause of discontent. Eliminating it progressively each day is attaining wisdom.','Only the wise can be moderate. The middle path is a safe bet for peaceful life.'] },
      { title: 'The Cost', question: 'What does it cost to insist the world comply with you?', aphorisms: ['Most of our unhappiness is caused by insisting that the world concurs with our desires, howsoever unreasonable.','Helping your neighbour is betraying your desire to orgasm in her helplessness. You cannot help her who has not learnt to help herself.','Seek not happiness but wisdom; happiness shall follow as a consequence.','Freedom is but absence of anxiety; Liberty is limited by our imagination.'] },
      { title: 'Unlearning', question: 'Is unlearning also a form of education?', aphorisms: ['Thoughts precede actions but actions can modulate emotions; acting happy can actually make you happy.','The wise shield themselves from diversionary knowledge which is pouring in from all direction. Employment of mental hygiene is mark of a wise person.','To unlearn the absorptions of innocence and acceptance is also great education.','Wisdom is the apex of strength in front of which everything is weaker.'] },
      { title: 'The Path', question: 'Is poverty a condition of the hand, or the mind?', aphorisms: ['Most sicknesses can be cured by abstinence and total rest. Investing intellectual capital in oneself is necessary to develop these traits.','Poverty is more in thought than in possessions. Development of thought is the prerequisite for eliminating poverty.','It is better to take a path less trodden to find your centre. Safe paths are diversionary and can only produce sub par.','We have no right to inflict pain, physical or emotional, on anybody, howsoever close or far the person is.'] },
      { title: 'The Refusal', question: 'What does the wise person quietly refuse?', aphorisms: ['Man is the only animal capable of flattening hierarchy without struggle. He approximates animals when he insists on hierarchical divisions.','Men have inbuilt proclivities and must be allowed to proceed their way. They should not attempt to make fire descend or water to rise. Energy and effort spent to attempt otherwise will dissipate soon.','To will more than your capacity is the sign of an evolved person. Ordinary pursuits are for the majority.','Past reputations are illusory; never get taken in by such illusions. Everybody should be judged on the anvil of the present.'] },
      { title: 'The Silence', question: 'Can one be connected and alone at the same time?', aphorisms: ['A wise person will not have any enemies just as no friends for she considers both are spirit-sapping. Acquaintances are acceptable for momentary transactional uptakes.','The wise prefer silence.','Wisdom is to realise that your knowledge is minuscule in this infinite universe yet you can be content.','Live for yourself fully. In that way, you can help others to live their lives fully.'] },
      { title: 'The Curtain', question: 'What curtain, once lifted, cannot be lowered again?', aphorisms: ['To judge the scheme of things in your world from your limited perspective is to cause gashes on your happiness.','Security is an illusion. Only they live who jettison security and choose freedom.','No man is an island and everything is connected yet each one is a pole and everyone bears responsibility towards him.','Only when she takes off the curtain of the divine that she can really appreciate the infinite beauty of the universe.'] }
    ]
  },
  {
    id: 4, name: 'Love & Relationships', symbol: '♾', color: '#c25a2a',
    question: 'Is love an act of giving, or of emptying oneself?',
    cards: [
      { title: 'The Giving', question: 'Is love an act of giving, or of emptying oneself?', aphorisms: ['True love is a speck of the divine; lovers can claim divinity in themselves. But the jealous world would have nothing of it so it batters them with the stupidity of social order and morals.','Marriage is a social convenience; to make it a perpetual, divine obligation is a fraud perpetrated by the weak upon the strong.','Love and sex are related and one may lead to the other. But they are two distinct phenomena and can exist independent of each other.','Sex is animal instinct for procreation; giving unto it, though enthralling, can bring social sanctions upon the unsuspecting. Discretion should be the watchword whilst indulging it.'] },
      { title: 'The Stronger', question: 'Who is truly the stronger sex?', aphorisms: ['Strange that women are considered weaker sex when they do the hardest labour, suffer worst pain monthly, bear childbirth pains with pleasure. Men would fold up with such agony.','Men are afraid of women because they know that men are dispensable. Women can do without men but the reverse is impossible.','Men know that one man can impregnate hundred women and make the ninety nine superfluous — hence the song of morality, social order, institution of marriage, widow immolation, etc.','One woman can moderate mans animal instincts but if three women together decide, they can make a brute into a decent human person.'] },
      { title: 'The Distance', question: 'What distance does comfort quietly introduce?', aphorisms: ['Large houses leave too much gap and distance in relations.','Love is giving your self to the other; you cannot love if there is even a bit of yourself within you.','Tears have a strange charisma in them; others just cannot refuse what tears demand.','Marriage is sacrificing creativity and adventure for the sake of security.'] },
      { title: 'The Universal', question: 'Is love universal, or does confining it make it love at all?', aphorisms: ['Only children borne out of love deserve our love. Others born out of transient passion don\'t deserve that privilege.','Love can overcome most reasonable obstacles.','Women civilize the brute in men. That is why Mother Mary is prayed to more than Jesus or Moses.','Compassion and love are limitless; to confine them to a few objects is denying their universality.'] },
      { title: 'The Object', question: 'When love fixes on an object, what does it become?', aphorisms: ['Anger is madness but so is love.','Love is without an object. It becomes selfish as it hurtles towards an object.','Affection elevates just as jealousy depresses; affectation of the spirit is the bane of our times which sucks up affection.','Only those who are becoming better or worse morally, no matter how venal or saintly they have been, deserve our respect or contempt. Past conditions are of no consequence in the present.'] }
    ]
  },
  {
    id: 5, name: 'Nature & Mortality', symbol: '∿', color: '#1e6b52',
    question: 'Are we the drop, or do we become the pond?',
    cards: [
      { title: 'The Pond', question: 'Are we the drop, or do we become the pond?', aphorisms: ['Human person is but a drop in this universal pond; its destiny is to realize its worth by becoming one with the pond.','Instincts make the birds fly and fish to swim. A free person can also live likewise if he chooses.','Death is the end of all misery; fear of death can desiccate the living.','It is easy to understand the language of plants and animals because they have bare minimum vocabulary.'] },
      { title: 'The Ghost', question: 'What do we feed, and what feeds us?', aphorisms: ['The idea of soul is even less useful than the sole of your shoes.','You should welcome Ghosts for they are reflections of your subconscious.','We have forgotten the beauty of the moon or a starlit night. The blinding Sun has absorbed our being.','To consume without conscious awareness, whether meat or vegetable, is denying our due to nature; just as the fruit gives us sustenance, so do we feed the eternal tree of life.'] },
      { title: 'The Bloom', question: 'Is the relationship between man and world a wound, or a bloom?', aphorisms: ['Let the bird in your heart, the river in your feet, the sun in your consciousness seek the eternal universe; it is the noblest pursuit.','Nature is impartial. It kills without discrimination.','Death is like the sun; it was, is and will be there. It is upto us to absorb its warmth and recreate life.','A man\'s relationships with the surroundings should be like the bee and the bloom; none is hurt and both thrive.'] },
      { title: 'The Senses', question: 'What have we lost, sense by sense?', aphorisms: ['We have almost lost our sense of smell to the exclusion of sight or touch. With progressive homogeneity of foods, we may also lose the sense of taste.','All human progress in our world is against nature. Its beauty is but the illusion in your senses.','Once we stopped growing we surrender to death. Life is perpetual growth; the dead only decay.','Waiting for death to claim the spirit is the most miserable of existence; we should claim death once we stopped creating.'] },
      { title: 'A Good Death', question: 'What makes a death beautiful?', aphorisms: ['Death is beautiful when it comes while creating beauty, wisdom and spreading love.','Life teaches us nothing except what we learn from others misery.','To be interested in food is loving life; gluttony is contempt for life.'] }
    ]
  },
  {
    id: 6, name: 'Knowledge & Education', symbol: '⊕', color: '#9a7a10',
    question: 'What use is a diamond to a hungry woman?',
    cards: [
      { title: 'The Diamond', question: 'What use is a diamond to a hungry woman?', aphorisms: ['Truth is but a reflection of our desires. Quest of the truth is falling in that trap of frustrating nothingness.','It is stupid to give useless pieces of diamonds to a hungry woman; she will throw it on garbage.','The Magi were ignorant and insensitive to bring incense and myhrr to Mary at childbirth of christ; if wise, they should have been practical with towels and fresh sheets.','Painting is primordial. Those who underestimate painting are subhuman and just above animals in their evolution.'] },
      { title: 'The Hunger', question: 'Is it the teacher\'s duty to give knowledge, or to create hunger for it?', aphorisms: ['The prime duty of an educator is to inspire her pupil; imparting knowledge and information could be a collateral.','Knowledge generally causes misery yet it is preferable to content-proffering ignorance.','You can give only what you have; what you have created is only for yourself — others may enjoy your creation but only as a collateral fallout.','Science is tentative and can be imbibed by anybody; learning is a function of time. But art is inborn and cannot be learned.'] },
      { title: 'The Cattle', question: 'What does an education that makes cattle also unmake?', aphorisms: ['Education is basically cultivation of the mind; it leads to improvements of thoughts, relationships, processes, implements, even life.','Education is a liberator but the type of education is important. The system to make cattle-like followers is debilitating.','Education helps in picking up knowledge scattered around to add value to the self.','Education is most effective when it is self-motivated and self driven.'] },
      { title: 'Music & Noise', question: 'Is music something we learn, or something we remember?', aphorisms: ['Education determines who will control and be controlled. This is the most decisive factor between the rulers and the ruled. Money is only secondary and muscle, only a distant tertiary factor.','Sounds can enhance or debase the harmony within. Cultures which develop ability to discriminate between the good and bad sounds will progress.','Music is poetry of life. Noise is destruction of life.','Space is indivisible provided your consciousness has fathomed it.'] },
      { title: 'The Child', question: 'When does the child deserve the whole sky?', aphorisms: ['Children are but creatures of life\'s quest for life. None has an inherent right to dictate their journeys; parents, however, have an obligation to care till maturity.','Children are helpless till they are minors and weak; once they gain strength they need to reclaim the whole of the sky to splash their creativity.','Children are selfish brutes and would not hesitate to kill but for socialising influences and prohibitions.','Never be deceived by childlike visage. Children absorb adult guile rather rapidly.'] },
      { title: 'The Herbivore', question: 'Does what we eat reveal what we believe?', aphorisms: ['Don\'t believe that vegetarianism produces weakness. In fact most powerful animals are herbivores.'] }
    ]
  },
  {
    id: 7, name: 'Vice & Virtue', symbol: '⇌', color: '#6e2e82',
    question: 'Is the person without vice the most dangerous among us?',
    cards: [
      { title: 'No Vices', question: 'Is the person without vice the most dangerous among us?', aphorisms: ['Beware of the person who has no vices; he will avenge his punishment of deprivation by being utterly vicious.','Avarice is born, like any vice, out of ignorance and lack of wisdom.','Gluttony is the curse of our age. It may lead to demise of our civilisation.','The stupidity of caring for offsprings even after their adulthood will lead to civilisational decline.'] },
      { title: 'The Genius', question: 'Is suffering the price genius pays, or its condition?', aphorisms: ['Geniuses are born to suffer on behalf of humanity.','Patriotism is social inferiority turned inside out.','Humility is the acceptable aspect of inadequacy.','There is no pleasure greater than chopping one\'s vanity.'] },
      { title: 'Certainty', question: 'Is certainty the mark of the educated, or its opposite?', aphorisms: ['Uneducated people are always certain of their views; educated people are sceptical and tentative.','Certainty is indicative of ignorance.','Rigidity is a child of inferiority.','Pride is a hollowed facade of a petty mind. Sometimes it takes the visage of self-respect. Both are brothers in arm.'] },
      { title: 'Mercy', question: 'Does mercy extend misery, or end it?', aphorisms: ['Jealousy is shooting an arrow onto oneself; its genesis is total ignorance.','Mercy is but extending the misery of the defeated soul.','Indifference to evil is being accessory to evil.','To complain about a situation is sub-human. To attempt its amelioration is approaching its reach to manhood.'] },
      { title: 'Inequality', question: 'Is inequality the root of all we cherish and all we destroy?', aphorisms: ['The most evil aspect of inequality is its opportunity cost. It has inhibited endless creativity.','Inequality is evil through and through but it is also a precursor of everything cherishable.','Beware of the narcissist for she will go to any length to seek approval and praise.','There is some charisma implicit in bastard men. Most figures in the Christian or Indian pantheon were bastards — rationalised as children of forces other than their fathers in the worldly sense.'] },
      { title: 'Compassion', question: 'Where does compassion end and passion begin?', aphorisms: ['Compassion is love for others happiness, passion for self. Both should be there but with discretion.'] }
    ]
  },
  {
    id: 8, name: 'Beauty & Art', symbol: '◈', color: '#1a4f8a',
    question: 'Is beauty a fact of the world, or a discipline of perception?',
    cards: [
      { title: 'Proportion', question: 'Is beauty a fact of the world, or a discipline of perception?', aphorisms: ['Beauty is symmetry and proportion. Modernity is somehow bent on distorting this axiom.','Those who cannot appreciate beauty do not deserve to live; they seemingly have lost that sense which brings joy within.','Beauty is only proportion. Even slight excess of anything worth appreciating will destroy that beauty — be it size, colour, flavour, form.','To create beauty is reaching pinnacle of human existence.'] },
      { title: 'The Moon', question: 'What does it cost us to have forgotten the moon?', aphorisms: ['Music cures just as Noise desecrates. To know the difference is wisdom.','We have forgotten the beauty of the moon or a starlit night. The blinding Sun has absorbed our being.','Intoxication is temporary suspension of your anxieties. They will attack with greater vigour soon.'] }
    ]
  },
  {
    id: 9, name: 'Work & Property', symbol: '⧖', color: '#7a4010',
    question: 'When does the thing we own begin to own us?',
    cards: [
      { title: 'The Owner', question: 'When does the thing we own begin to own us?', aphorisms: ['Work should be uplifting rather than degrading; those who don\'t find happiness in their work are doubly doomed.','The idea of profit, unless modulated by self-limiting, is abominable and cause of great evil.','Traders facilitate production and welfare but inhibit creativity and content. They sap away the pleasure inherent in creativity.','The problem with property is that it enslaves the owner.'] },
      { title: 'The Cage', question: 'Is the cage we choose less a cage for the choosing?', aphorisms: ['Property fosters production of material gain but induces disproportionately unequal loss in morale and therefore dehumanisation.','To be cooped in costly abodes is denying freedom to the human spirit.','It is ironical that man is progressively choosing the security of the cage rather than the freedom of the sky and vast beautiful expanse.','Work is demeaning if there is no love of it. Labour of love is sweet and most fulfilling.'] },
      { title: 'The Hand', question: 'What does the human hand add that nature alone cannot?', aphorisms: ['Food in its raw form, though life-sustaining, is not life enhancing; it needs human inputs to enhance its efficacy.'] }
    ]
  },
  {
    id: 10, name: 'Death & Acceptance', symbol: '◯', color: '#1a3a5c',
    question: 'What does fifty years give us, if not a resting place within ourselves?',
    cards: [
      { title: 'Fifty Years', question: 'What does fifty years give us, if not a resting place within ourselves?', aphorisms: ['Those who have lived over fifty years and still groping for ways of solace don\'t deserve even that knowledge, let alone wisdom to be content.','If given a choice of boons, I would choose wisdom — in preference to wealth, power, health, happiness or love.','Softer beds give lumbar pain and make broken backs.','Life for Those who are denied indulgences is dry; they seek compensation by with dominance and unnecessary restrictions on others.'] }
    ]
  },
  {
    id: 11, name: 'Instinct & Authenticity', symbol: '⟡', color: '#b06a10',
    question: 'Is foresight the only quality that survives the race?',
    cards: [
      { title: 'Foresight', question: 'Is foresight the only quality that survives the race?', aphorisms: ['Only people with foresight will succeed in the rat-race of life even without any endearing qualities of life.','Defeat follows drooping of shoulders.','It is easy to understand the language of plants and animals because they have bare minimum vocabulary.','Don\'t believe that vegetarianism produces weakness. In fact most powerful animals are herbivores.'] },
      { title: 'The Forbidden', question: 'How does the wise person taste what is forbidden without being consumed by it?', aphorisms: ['Things forbidden are the juiciest; wise men absorb the juice without touching the thing.','Seek pleasures of the mind. Bodily pleasures generally debilitate.','Happiness is an illusion; the more you pursue, the farther it goes.','Your world waits not, like sun or moon, for you. Make the most of it while you can.'] }
    ]
  },
  {
    id: 12, name: 'Judgment & Perspective', symbol: '⊿', color: '#3a5c3a',
    question: 'Can we ever know enough to judge fairly — and if not, what then?',
    cards: [
      { title: 'The Judge', question: 'Can we ever know enough to judge fairly — and if not, what then?', aphorisms: ['Don\'t judge till you have known all facts, including each of their aspects, which is an impossibility.','Give not an unasked opinion for it will boomerang. Opinion, if asked, should be only given in the form of questions.','Being good is not enough; goodness should be accompanied by intelligence for happiness.','Discretion is necessary while giving; it should not add to the evil which lies within the recipient.'] },
      { title: 'The Noble', question: 'What separates those who discuss ideas from those who merely discuss people?', aphorisms: ['Base men discuss events; baser still discuss persons. Noble men discuss ideas; nobler still discuss principles. The wise do not discuss.','Templates are for the indolent. Hazards are for the enterprising.','It is ironical that Buddha the wisest is pictured with half closed eyes, when his eyes were more open than anybody around.','Man, because he is more evolved and developed, bears responsibility to look after everything in this world.'] },
      { title: 'The Albatross', question: 'Is reaching for the supernatural a sign of how far we\'ve come, or how far we still must go?', aphorisms: ['It is a travesty that man has developed so far yet development has become an albatross, relief from which is sought by seeking help from the supernatural.','No man is an island and everything is connected yet each one is a pole and everyone bears responsibility towards him.','To judge the scheme of things in your world from your limited perspective is to cause gashes on your happiness.'] }
    ]
  }
];
